--- #YAML:1.0
name: Quota
abstract: Quota - Perl interface to file system quotas
version: 1.6.6
author:
  - Tom Zoerner <tomzo@users.sourceforge.net>
license: perl
distribution_type: module
keywords:
  - quotactl
excludes_os: MSWin32
no_index:
  directory:
    - contrib
resources:
  license: http://dev.perl.org/licenses/
